############################
###     DATA SECTION     ###
############################

# features are the names of the input variables
# - el1_etas1
# - el1_etas2
# - el2_etas1
# - el2_etas2
# - el1_maxEcell_E
# - el2_maxEcell_E
# - el1_maxEcell_x
# - el2_maxEcell_x
# - el1_maxEcell_y
# - el2_maxEcell_y
# - el1_maxEcell_z
# - el2_maxEcell_z
# - el1_maxEcell_t
# - el2_maxEcell_t
# - el1_sinh_etas12
# - el2_sinh_etas12
# - el1_maxEcell_R
# - el2_maxEcell_R
# - el12_maxEcell_R
# - el1_diff_etas12
# - el2_diff_etas12
# - el12_diff_maxEcell_x
# - el12_diff_maxEcell_y
# - el12_diff_maxEcell_z
# - el1_dca
# - el2_dca
# - el1_eta
# - el2_eta
# - el1_phi
# - el2_phi
# # - el1_phis1
# # - el1_phis2
# # - el2_phis1
# # - el2_phis2
# - el1_pt
# - el2_pt
# - el1_E
# - el2_E
# - el1_t
# - el2_t
# - Zcand_M
# - Zcand_pt
# - dPhi_el
# - dEta_el
# # - el1_f1
# # - el1_f3
# # - el2_f1
# # - el2_f3

features:
  - el1_etas1
  - el1_etas2
  - el2_etas1
  - el2_etas2
  - el1_maxEcell_E
  - el2_maxEcell_E
  - el1_maxEcell_x
  - el2_maxEcell_x
  - el1_maxEcell_y
  - el2_maxEcell_y
  - el1_maxEcell_z
  - el2_maxEcell_z
  - el1_maxEcell_t
  - el2_maxEcell_t
  - el1_sinh_etas12
  - el2_sinh_etas12
  - el1_maxEcell_R
  - el2_maxEcell_R
  - el12_maxEcell_R
  - el1_diff_etas12
  - el2_diff_etas12
  - el12_diff_maxEcell_x
  - el12_diff_maxEcell_y
  - el12_diff_maxEcell_z
  - el1_dca
  - el2_dca
  - el1_eta
  - el2_eta
  - el1_phi
  - el2_phi
  - dEta_el
  - el1_phis1 # remove for 1D predictions
  - el1_phis2 # remove for 1D predictions
  - el2_phis1 # remove for 1D predictions
  - el2_phis2 # remove for 1D predictions
  - el1_pt
  - el2_pt
  - el1_E
  - el2_E
  - el1_f1
  - el1_f3
  - el2_f1
  - el2_f3
  - PassTrig_g35_loose_g25_loose
  - PassTrig_g35_medium_g25_medium
  # - lifetime
  # - signal_type
  # - mass_point
  - Zcand_M
  - el1_t
  - el2_t
  - Zcand_pt
  - dPhi_el
  
# targets are the names of the output variables, i.e. the variables we 
# want to predict
targets:
  - PV_x
  - PV_y
  - PV_z
  - PV_R

# ignore_train is a list of variables that overrides the features and targets
# lists. Elements of ignore_train will still be loaded and preprocessed, but 
# will be dropped before training. This has tpwo primary use cases:
# 1. If you want to use a variable as input for a composite variable, but not
#    as an input to the model itself.
# 2. If you want to load the variable to use it for plotting or analysis, but
#    not for training.
ignore_train:
  # - el1_pt
  # - el2_pt
  # - el1_E
  # - el2_E
  # - el1_phi
  # - el2_phi
  # - el1_eta
  # - el2_eta
  # - dEta_el
  # - el1_t
  # - el2_t
  # - Zcand_M
  # - Zcand_pt
  # - dPhi_el
  # - dEta_el
  - el1_phi
  - el2_phi
  - PassTrig_g35_loose_g25_loose
  - PassTrig_g35_medium_g25_medium
  - PV_x
  - PV_y
  - el1_eta
  - el2_eta
  - Zcand_pt
  - dPhi_el

input_shape: auto
output_shape: auto

cut_name: Zee

# fraction of original root data to load
load_fraction: 0.99

test_split: 0.8
validation_split: 0.05

# data_path is the path to the raw data file relative to main.py
data_path: ../data/output_ZeeMC_test.root

# if the data is stored below a branch in the root file, specify the branch name
# NOTE: this currently only works for one superbranch
superbranch: PostSelZee

active_data_path: active_data         # should rename to active_data_dir
active_plots_path: active_plots
base_path: /Users/benls/workdir/projects/utatlas/neural-llp
archive_path: /Users/benls/workdir/projects/utatlas/neural-llp/box/NeuralLLP
checkpoint_path: /Users/benls/workdir/projects/utatlas/neural-llp/active_data


###############################
###     NETWORK SECTION     ###
###############################

learning_rate: 0.001
batch_size: 500
num_epochs: 100
# num_iter_per_epoch: 60
verbose_epochs: 1

# Model compile parameters
loss: mean_squared_error
optimizer: adam
metrics: 
  - mean_squared_error
  - mean_absolute_percentage_error
  # - mean_absolute_error
  - r_square
run_eagerly: True

EarlyStopping:
  - enable: True
  - monitor: loss
  - patience: 5
  - min_delta: 0.0001
  - verbose: 1
  - mode: min
  - restore_best_weights: True
# ModelCheckpoint:
#   - enable: True
#   - filepath: models/model.h5
#   - monitor: val_loss
#   - save_best_only: True
# ReduceLROnPlateau:
#   - enable: True
#   - monitor: val_loss
#   - factor: 0.1
#   - patience: 3
#   - min_lr: 0.00001

# how many digits should be displayed in the printed output
display_precision: 4


###########################
###     PLOT SECTION    ###
###########################

pointing_bins: 
  lower: 0
  upper: 120
  step: 20